apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Monitor-Cluster
  region: us-east-1

vpc:
  id: vpc-0#############
  cidr: "192.168.0.0/16"
  subnets:
    public:
      my-new-stack-PublicSubnet01:
        id: subnet-0#############
      my-new-stack-PublicSubnet02:
        id: subnet-0#############
    private:
      my-new-stack-PrivateSubnet01:
        id: subnet-0################
      my-new-stack-PrivateSubnet02:
        id: subnet-0################

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.micro
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.micro
    desiredCapacity: 1
    privateNetworking: true